# Evolution params
evolution_params:
  n_generations: 200
  population_size: 200
  remove_population_pct: 0
  n_elites: 0
  mutation_rate: 0.1
  mutation_factor: 0.1
  save_path: examples/constraints/context/results/triangle-penalty

prescriptor_params:
  model_params:
    - type: linear
      in_features: 4
      out_features: 64
    - type: relu
    - type: linear
      in_features: 64
      out_features: 64
    - type: relu
    - type: linear
      in_features: 64
      out_features: 2
  device: mps

problem: triangle
eval_params:
  n_jobs: 1
  device: mps