# Evolution params
evolution_params:
  n_generations: 100
  population_size: 200
  remove_population_pct: 0
  n_elites: 0
  mutation_rate: 0.1
  mutation_factor: 0.1
  save_path: examples/constraints/context/results/relu

prescriptor_params:
  model_params:
    - type: linear
      in_features: 1
      out_features: 16
    - type: relu
    - type: linear
      in_features: 16
      out_features: 16
    - type: relu
    - type: linear
      in_features: 16
      out_features: 2
  device: mps

eval_params:
  n_jobs: 1
  device: mps