# Evolution params
evolution_params:
  n_generations: 10
  population_size: 100
  remove_population_pct: 0.8
  n_elites: 0
  mutation_rate: 0.1
  mutation_factor: 0.1
  save_path: temp
  seed_dir: null

# Prescriptor-specific params
prescriptor_params:
  device: cpu

# Evaluation params
eval_params:
  n_steps: 1000
  n_envs: 4
