# Evolution params
evolution_params:
  n_generations: 400
  population_size: 200
  remove_population_pct: 0
  n_elites: 0
  mutation_rate: 0.1
  mutation_factor: 0.1
  save_path: tests/temp

# Prescriptor-specific params
prescriptor_params:
  xl: [-10, -10]
  xu: [10, 10]

# Evaluation params
eval_params:
  n_jobs: 1
